"""
Verification & Test Suite for CareDOM Autonomous Multi-Agent System.
Simulates a multi-agent diagnostic session and prints the full inter-agent message trace.
"""

import sys
if hasattr(sys.stdout, 'reconfigure'):
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

import time
import json
from ai_engine.agents.workflow import MultiAgentWorkflowEngine

def main():
    print("=" * 85)
    print("🤖 CareDOM Autonomous Multi-Agent Collaborative System — Execution Test")
    print("Team KYZER | Build with AI: Code for Communities 2")
    print("=" * 85)

    engine = MultiAgentWorkflowEngine()

    st = time.perf_counter()
    state = engine.run_workflow(
        country_code="IND",
        target_facility_id="PHC-PUN-002",
        target_item_code="MED-ORS-PKG"
    )
    elapsed_sec = time.perf_counter() - st

    print(f"\n[WORKFLOW ID]: {state.workflow_id}")
    print(f"[STATUS]: {'SUCCESS (Approved by Supervisor)' if state.is_completed else 'FAILED'}")
    print(f"[TOTAL AGENTS ENGAGED]: 5 Specialized Agents")
    print(f"[EXECUTION LATENCY]: {elapsed_sec * 1000:.2f} ms\n")

    print("=" * 85)
    print("📡 INTER-AGENT MESSAGE BUS & AUDIT TRACE")
    print("=" * 85)
    for idx, msg in enumerate(state.agent_message_log, 1):
        print(f"\nMessage #{idx} | [{msg.timestamp[11:19]}] | Priority: {msg.priority}")
        print(f"  From: [{msg.sender_agent}]  --->  To: [{msg.recipient_agent}]")
        print(f"  Type: {msg.message_type}")
        print(f"  Payload: {json.dumps(msg.payload, indent=4)}")

    print("\n" + "=" * 85)
    print("📋 WORKFLOW STEP TRANSITIONS (STATE GRAPH)")
    print("=" * 85)
    for step in state.execution_steps:
        print(f"  ✓ {step}")

    print("\n" + "=" * 85)
    print("💬 FINAL CLINICAL BRIEFINGS GENERATED BY EXPLAINER AGENT")
    print("=" * 85)
    print(f"English: \"{state.multilingual_narratives.get('english_narrative', '')}\"")
    print(f"Hindi:   \"{state.multilingual_narratives.get('hindi_narrative', '')}\"")
    print("=" * 85)

if __name__ == "__main__":
    main()
